resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 1Gi
  java_opts:
    - "-server -Xms1G -Xmx1G"
    - "-XX:+UseContainerSupport"
    - "-XX:+AlwaysActAsServerClassMachine"