namespace: default

deployment:
  replicas: 1
  restart_policy: Always
  image_pull_policy: Never

  health:
    progress_deadline_seconds: 90 # 10 + initial_delay_seconds + (period_seconds * failure_threshold)
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 1
    failure_threshold: 5