automerge:
  - '**'

source:
  - 'src/main/**'

test:
  - 'src/test/**'

devops:
  - '.*/**'
  - 'Dockerfile'
  - 'Makefile'

config:
  - '.*'
  - '*.gradle'
  - '*.config'

community:
  - '*.md'
  - 'LICENSE'