version: "3.3"
services:
  geomagnetic-database:
    container_name: geomagnetic-database
    image: postgres:9.5-alpine
    ports:
      - 5432:5432
    environment:
       POSTGRES_DB: geomagnetic
       POSTGRES_USER: geomagnetic
       POSTGRES_PASSWORD: geomagnetic
    volumes:
      - ./postgres/geomagnetic_init.sql:/docker-entrypoint-initdb.d/geomagnetic_init.sql
    restart: always

  config-service:
    build:
      config-service/
    image: weather/config-service:native
    ports:
      - 8888:8888
    environment:
      CONFIG_SERVICE_OPTS: $CONFIG_SERVICE_OPTS

  geomagnetic-api:
    depends_on:
      - geomagnetic-database
      - config-service
    build:
      geomagnetic-api/
    image: weather/geomagnetic-api:native
    ports:
      - 8001:8001