version: "3.7"

volumes:
  postgres:

services:
  geomagnetic-database:
    container_name: geomagnetic-database
    build:
      postgres/
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
    restart: on-failure

  config-service:
    build:
      config-service/
    image: illine/config-service:${DOCKER_TAG}
    ports:
      - 8888:8888
    environment:
      CONFIG_SERVICE_OPTS: $CONFIG_SERVICE_OPTS
    restart: on-failure

  geomagnetic-api:
    depends_on:
      - geomagnetic-database
      - config-service
    build:
      geomagnetic-api/
    image: illine/geomagnetic-api:${DOCKER_TAG}
    ports:
      - 8001:8001
    restart: on-failure