config_service_spring:
  spring:
    application:
      name: config-service
    cloud:
      config:
        server:
          native:
            search-locations: classpath:/shared
config_service_server:
  server:
    port: "{{ config_service_port }}"
    servlet:
      context-path: "{{ config_service_context_path }}"