server:
  port: 8000

management:
  server:
    port: 7000
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

spring:
  application:
    name: geomagnetic
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: geomagnetic
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/weather
    username: weather
    password: weather
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: HikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: geomagnetic
  groovy:
    template:
      check-template-location: false
  liquibase:
    enabled: false
  sleuth:
    web:
      client:
        enabled: false
  cloud:
    kubernetes:
      enabled: false
  security:
    api-key:
      enabled: true
      header-name: X-Api-Key-Authorization
      access-keys:
        - 0f1f16dc-5731-4f47-93ed-3d69943a1d7d

logbook:
  strategy: body-only-if-status-at-least
  include:
    - /forecasts/*
    - /services/*
  format:
    style: http
  logger:
    name: GEOMAGNETIC-REST

application:
  rest:
    max-thread: 100
    max-route: 10
    read-timeout: 15000
    connection-timeout: 10000
    retry:
      delay-in-ms: 500
      max-attempts: 5

  swpc-noaa:
    schema: https
    host: services.swpc.noaa.gov
    path: /text/3-day-geomag-forecast.txt

  etl:
    scheduled:
      enabled: true
      cron: "0 0 0/1 * * ?" # Every hour

  swagger:
    title: Geomagnetic Restful API
    description: Module maneges Geomagnetic Forecast
    version: v1
    licence-url: https://github.com/Illine/geomagnetic/blob/develop/LICENSE
    owner-name: Evgeniya Kovtun
    owner-url: https://github.com/Illine
    owner-email: eekovtun@gmail.com