server:
  port: 8000
  servlet:
    context-path: /weather
spring:
  application:
    name: geomagnetic-api
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5000/geomagnetic
    username: geomagnetic
    password: geomagnetic_1234
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: GeomagneticHikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: geomagnetic
  liquibase:
    enabled: false