server:
  port: 8000

spring:
  application:
    name: geomagnetic
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: geomagnetic
    open-in-view: false
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/weather
    username: weather
    password: weather
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: HikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: geomagnetic
  liquibase:
    enabled: false

logbook:
  strategy: body-only-if-status-at-least
  exclude:
    - /actuator/*
  format:
    style: http
  logger:
    name: GEOMAGNETIC-REST
    level: INFO

rest:
  maxThread: 100
  maxRoute: 10
  readTimeout: 15000
  connectionTimeout: 10000
  retry:
    delay-in-ms: 500
    max-attempts: 5

swpc-noaa:
  schema: https
  host: services.swpc.noaa.gov
  path: /text/3-day-geomag-forecast.txt

etl:
  scheduled:
    enabled: true
    cron: "0 0 0/1 * * ?" # Every hour