resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Gi
  java_opts:
    - "-server -Xms256M -Xmx512M"
    - "-XX:MaxRAMPercentage=85.0"
    - "-XX:+UseContainerSupport"
    - "-XX:+AlwaysActAsServerClassMachine"