namespace: prod

deployment:
  replicas: 2
  restart_policy: Always

  health:
    progress_deadline_seconds: 450
    initial_delay_seconds: 300
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 12