spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: geomagnetic
    open-in-view: false
  datasource:
    url: jdbc:p6spy:postgresql://geomagnetic-postgres:5432/geomagnetic
    username: geomagnetic
    password: geomagnetic
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: DevHikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: geomagnetic
  liquibase:
    url: jdbc:postgresql://geomagnetic-postgres:5432/geomagnetic
    default-schema: geomagnetic
    user: geomagnetic
    password: geomagnetic
    change-log: classpath:liquibase/changelog.yaml
    contexts: dev
logging:
  pattern:
    console: "%d{ISO8601} [%thread] [%-5level] [%logger{36}] - %msg%n"
  level:
    GEOMAGNETIC-EXCEPTION-HANDLER: DEBUG
    GEOMAGNETIC-UTIL: DEBUG
    GEOMAGNETIC-MAPPER: DEBUG
    GEOMAGNETIC-ACCESS: DEBUG
    GEOMAGNETIC-SERVICE: DEBUG
    GEOMAGNETIC-SQL: DEBUG
    GEOMAGNETIC-CLIENT: DEBUG
    GEOMAGNETIC-EVENT: DEBUG
    GEOMAGNETIC-SCHEDULE: DEBUG
    root: INFO
server:
  port: 8001
  servlet:
    context-path: /geomagnetic
rest:
  maxThread: 100
  maxRoute: 10
  readTimeout: 15000
  connectionTimeout: 10000
  swpNoaa:
    schema: https
    host: services.swpc.noaa.gov
    path: /text/3-day-geomag-forecast.txt
schedule:
  forecast:
    cron: 0 0/2 * * * ? # Every 2 min