spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: geomagnetic
    open-in-view: false
  datasource:
    url: jdbc:p6spy:postgresql://geomagnetic-database:5432/weather
    username: geomagnetic
    password: geomagnetic
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: NativeHikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: geomagnetic
  liquibase:
    url: jdbc:postgresql://geomagnetic-database:5432/weather
    default-schema: geomagnetic
    user: geomagnetic
    password: geomagnetic
    change-log: classpath:liquibase/changelog.yaml
    contexts: native
  groovy:
    template:
      enabled: false
      check-template-location: false
rest:
  max-thread: 100
  max-route: 10
  read-timeout: 15000
  connection-timeout: 10000
  swp-noaa:
    schema: https
    host: services.swpc.noaa.gov
    path: /text/3-day-geomag-forecast.txt
schedule:
  forecast:
    cron: 0 0/2 * * * ? # Every 2 min