---
k8s:
  directory:
    configs: "{{ playbook_dir }}/configs/k8s"
    templates: "{{ playbook_dir }}/roles/{{ role_name }}/templates/k8s"
  files:
    - config-map.yaml
    - deployment.yaml
    - secret.yaml
    - service.yaml

liquibase:
  directory:
    configs: "{{ playbook_dir }}/configs/liquibase"
    templates: "{{ playbook_dir }}/roles/{{ role_name }}/templates/liquibase"
  files:
    - liquibase.properties