spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          ignore-local-ssh-settings: true
          search-paths: "{application}/{profile}"
          private-key: "${DISCOVERY_CONFIG_SSH_KEY}"
          uri: "${DISCOVERY_CONFIG_SSH}"
server:
  port: 8888
  servlet:
    context-path: /config-service