name: "release"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          architecture: x64
          java-version: 11

      - name: Gradle Test
        run: ./gradlew test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/jacoco/coverage.xml
          name: codecov-geomagnetic-unit
          flags: unit
          fail_ci_if_error: true

  build:
    if: github.event_name == 'push'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          architecture: x64
          java-version: 11

      - name: Gradle Cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle Build
        run: ./gradlew assemble

      - name: Upload JAR
        uses: actions/upload-artifact@v1
        with:
          name: geomagnetic.jar
          path: build/libs/geomagnetic.jar

  docker:
    if: github.event_name == 'push'
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download JAR
        uses: actions/download-artifact@v1
        with:
          name: geomagnetic.jar
          path: build/libs/geomagnetic.jar

      - name: Docker build and push
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: illine/geomagnetic
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest