name: "release"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          architecture: x64
          java-version: 11

      - name: Gradle Test
        run: ./gradlew test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/jacoco/coverage.xml
          name: codecov-geomagnetic-unit
          flags: unit
          fail_ci_if_error: true

      - name: Gradle Build
        run: ./gradlew assemble

      - name: Tag Bump and Push
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false
          RELEASE_BRANCHES: master
          INITIAL_VERSION: 1.0.0

      - name: Docker Build and Push
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: illine/geomagnetic
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.build.outputs.tag }}"