name: "pull request"

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          architecture: x64
          java-version: 11

      - name: Gradle Test
        run: ./gradlew test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/jacoco/coverage.xml
          name: codecov-geomagnetic-unit
          flags: unit
          fail_ci_if_error: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'